### ISSUE TITLE
How to measure cumulative stats like Activity Monitor?

### ISSUE THREAD

**Issue by Sunil-P** [packetzero/libntstat#1]
My understanding =

Use the "id" field to determine the stream, and add tx and rx up all the ids per pid. 
But as you mentioned, 

`Stream ID provided by kernel. Unique for app runtime. Can rollover at uint32_t, so id can be reused.`
id can repeat, this makes the cumulative values incorrect. 

So how do we have cumulative values akin to activity monitor ?

**Comment by packetzero** [comment]
The IDs can be reused after an application has exited, but it's unlikely that will happen quickly.
Therefore, accumulating stats per stream ID is fine.  It's been a long while since I looked at this code, and it definitely could use some refactoring.  The new Endpoint Security API is easier to use, but requires that Apple grant you an entitlement.

**Comment by Sunil-P** [comment]
Yes, it seems big sur + this is no longer possible as apple may have patched the private socket stream. It kinda sucks as you will need an entitlements to do it. Ill close this issue, thanks a lot for replying

**Comment by packetzero** [comment]
wow, I didn't know they removed it in Big Sur.  Thanks for looking into this.
